# Generated by Django 3.0.6 on 2020-06-07 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_todomodel_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todomodel',
            old_name='user',
            new_name='creator',
        ),
    ]
